#!/usr/bin/env node
/**
 * Inline plugin skill bodies into a TS module at build time.
 *
 * Why: the bridge bundles to a single dist/index.js via tsup. Runtime-fs
 * resolution via `import.meta.url` is fragile post-bundle (splitting chunks,
 * npm install layouts). Codegen makes the skill bodies literally part of the
 * compiled output — zero runtime fs reads, zero path math.
 *
 * Source of truth: plugin/skills/<name>/SKILL.md
 * Output: bridge/src/mcp/prompts/inlined.ts (gitignored-safe; regenerated)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const skillsDir = resolve(repoRoot, 'plugin', 'skills');
const outFile = resolve(repoRoot, 'bridge', 'src', 'mcp', 'prompts', 'inlined.ts');

const SKILLS = [
  { key: 'finny_usage', dir: 'finny-usage' },
  { key: 'finny_judging', dir: 'judging-output' },
];

function stripFrontmatter(raw) {
  return raw.replace(/^---[\s\S]*?---\n/, '').trim();
}

const bodies = {};
for (const { key, dir } of SKILLS) {
  const p = resolve(skillsDir, dir, 'SKILL.md');
  const raw = readFileSync(p, 'utf8');
  const body = stripFrontmatter(raw);
  if (body.length < 500) {
    throw new Error(
      `inline-skills: ${p} body is ${body.length} chars after frontmatter strip; expected >500. Frontmatter regex drift?`
    );
  }
  bodies[key] = body;
}

const banner = `// AUTOGENERATED by bridge/scripts/inline-skills.mjs — do not edit by hand.
// Source: plugin/skills/<name>/SKILL.md (frontmatter stripped).
// Regenerated on every build via the "prebuild" script.
`;

const body = `${banner}
export const INLINED_SKILLS: Record<string, string> = ${JSON.stringify(bodies, null, 2)};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body, 'utf8');

// eslint-disable-next-line no-console
console.error(
  `inline-skills: wrote ${outFile} (finny_usage=${bodies.finny_usage.length}c, finny_judging=${bodies.finny_judging.length}c)`
);
